# name: CalibrationTarget
name: AT-200ProII
hw_version: '1.0'
sw_version: '2.0'

build_settings:
  development:
    processor: 18LF57K42
    programmer: Pickit4
    defines:
      - DEVELOPMENT
      # - USB_ENABLED
      - SHELL_ENABLED
      - SHELL_HISTORY_ENABLED
      - LOGGING_ENABLED

  release:
    processor: 18F26K42
    programmer: ICD-U80-win
    defines:
      - RELEASE
      # - USB_ENABLED
    
    skip_rules:
      - src/shellcommands/*
      - src/os/shell/*
      - src/os/json/*
      - src/os/judi/*
      - src/usb/*